modLoader = "kotlinforforge"
loaderVersion = "[4,)"
license = "GPL-3.0"

[[mods]]
modId = "chatplus"
version = "${file.jarVersion}"
displayName = "ChatPlus"
logoFile = ""
authors = "ebicep"
description = '''Minecraft chat improved'''

[[dependencies.chatplus]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.chatplus]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.21)"
ordering = "NONE"
side = "BOTH"